### ISSUE TITLE
How to update the metadata?

### ISSUE THREAD

**Issue by mrmagicli** [mar-file-system/GUFI#111]
hi,

when I want to use GUFI, I always want to have the newest metadata lists. Do I need to execute gufi_dir2index whenever I want to check the newest metadata? Or there have some methods can update the metadata in a specific period without executing command  manually？

**Comment by mrmagicli** [comment]
In the guide, I saw bfwreaddirplus2db may have this function, however when I execute this command , the terminal says "Segmentation fault"
![图片](https://user-images.githubusercontent.com/66016779/209625621-a54654c8-c037-4d1e-8604-f564edbeef65.png)

**Comment by garygrider** [comment]
There is no automated re-indexing
If you want to updated a part of the index tree you can run one of the many ways to create an index ( depending on your source file system ) and put that new index into a new place.  When complete, delete the old part of the index and move the new one into its place.  You could write a script to automate this based on your needs.

 gufi_dir2index Does not update an index tree in place, it just makes a new index and you replace the old one with the new index.  You can do it from any point in the tree.

Sent with BlackBerry Work
(www.blackberry.com)


From: mrmagicli ***@***.******@***.***>>
Date: Monday, Dec 26, 2022 at 11:13 PM
To: mar-file-system/GUFI ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [EXTERNAL] [mar-file-system/GUFI] How to update the metadata? (Issue #111)


hi,

when I want to use GUFI, I always want to have the newest metadata lists. Do I need to execute gufi_dir2index whenever I want to check the newest metadata? Or there have some methods can update the metadata in a specific period without execute manually？

**Comment by garygrider** [comment]
This function was used to build a gufi index tree from a an IBM DB2 database from an HPSS archive system.  To use this you would need to have DB2 and HPSS as a source storage system you are trying to index.

Sent with BlackBerry Work
(www.blackberry.com)


From: mrmagicli ***@***.******@***.***>>
Date: Tuesday, Dec 27, 2022 at 12:02 AM
To: mar-file-system/GUFI ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [mar-file-system/GUFI] How to update the metadata? (Issue #111)


In the guide, I saw bfwreaddirplus2db may have this function, however when I execute this command , the terminal says "Segmentation fault"
[??]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/66016779/209625621-a54654c8-c037-4d1e-8604-f564edbeef65.png__;!!Bt8fGhp8LhKGRg!GRv7-tBsMuCP2tGBSKAmOQDuRhpXD4g8lESYjYi2ybb6TdxJHWmqaTAz1qDAf35ITjPimrjAV5R3x6J8hctfO0Ra$>

**Comment by mrmagicli** [comment]
> 
Thank you.
You know, the source file system always be very large. So if I need to create a new index every time when I want to re-index, it will make an unpredictable impact on metadata server and will spend a lot of time. I spend 10 minutes to use gufi_dir2index to create an index for a directory with 2570000 files.

**Comment by garygrider** [comment]
What is the source file system?
Sounds like it has a metadata server, so maybe lustre or hpss?

As you know, figuring out what has happened to a tree is very difficult because of complex moves of large subtrees, the magic of mv.

With lustre we have been working on/considering three options.

1) use the lustre activity log, similar to how robinhood.  This would enable you to be able to replace only the subdirectories that have changes in them.  We are not fans of this approach at our site because turning on the activity log has caused instability at high scales.

2) use a lester like approach, where you scan the obsd file systems and use that to do a reverse lookup to see what subtrees have changes in them.  I think this is what we use but maybe our staff will reply on how.

3) probably the most promising approach, Cray (now hpe), since their Brindexer product is based on gufi (except it uses a hash so it can only be queried by root) is upstreaming a mod to the activity log.  To limit how much reindexing is needed and to limit massively how much logging needs to be done, they only log which subtrees have had changes in them.  They only log the top of the subtree, and so if a million changes occur in a subtree, there only is a single entry in the log.  Somehow they mark the subtree as dirty so they don’t log if the subtree is already dirty.  This is orders of magnitude less logging which is good for lustre and enables just reindexing small subsets of the total tree.

Other:
1) Of course using lustre metadata clustering is also an option
2) placing the index itself in the source metadata tree.  This has some goodness, in that moving parts of the tree takes care of itself so updating the index is far easier, you only care about files/links in a single directory, moving large subtrees requires no index change.  This has drawbacks thought.  You still need to walk the source tree to find what needs to be updated, although you could use the original activity log to make this faster.  It also puts the search load on the source file system which is not a good idea usually.  And of course you can’t make the index read only because the index debase files live in the users trees.
3) combinations of things like one site long ago was using robinhood for keeping a database up to date by replaying lustre logs, and wanted to load a gufi for users to query from the robinhood database periodically.  We had a way to walk the robinhood sql db to create a gufi tree, although not sure if that code works anymore but it could probably be revived.

You can see, there are lots of ways to put together the solution that is best for you.
If you are looking for keeping your index very up to date from a very large source tree, those are most of the possible huge helps for lustre.

It really depends on your situation as to what the solution is.  As you can see they are all trade offs.

We find that updating the index every few hours for our very active file systems is enough for users.  We think the Lester concept isn’t too bad as it leverages the parallelism in lustre ( the ost’s), but the new lustre logging that HPE/Cray is  up streaming may be eventually the best way as it reduces the logging by orders of magnitude.

If you are using HPSS, walking that system is pretty slow as it involves so many joins and permissions checks.  Going directly to DB2 is one answer.  I think there is also a logging ability in HPSS.

If you are Spectrum Scale/GPFS there is the shadow inode api.

Many fs’s honor the dmapi api which could be explored
Fanotify also seems to be of sone use as well.
There are many more tricks as well based on the FS and your use case.

As for is ten minutes good for rebuilding an index, I don’t really know.  One could try to speed that up by profiling a bit to see where the time is spent. It sounds slow to me but I don’t know what you are doing/using exactly.
Our staff might comment on our performance if we are doing something similar.  As I recall, when we buy lustre on an rfp we require hundreds of thousands to even millions of metadata ops / sec.  Maybe there is something you can do to speed up the reindexing process.

Anyway, I hope this discussion helps a little.






Sent with BlackBerry Work
(www.blackberry.com)


From: mrmagicli ***@***.******@***.***>>
Date: Wednesday, Dec 28, 2022 at 12:42 AM
To: mar-file-system/GUFI ***@***.******@***.***>>
Cc: Grider, Gary Alan ***@***.******@***.***>>, Comment ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [mar-file-system/GUFI] How to update the metadata? (Issue #111)


Thank you.
You know, the source file system always be very large. So if I need to create a new index every time when I want to re-index, it will make an unpredictable impact on metadata server and will spend a lot of time. I spend 10 minutes to use gufi_dir2index to create an index for a directory with 2570000 files.

**Comment by mrmagicli** [comment]
Thank you very much for your discussion.  Much help! Thanks.
